name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm i -g firebase-tools
      - run: yarn install --prod
      - run: yarn build
        env:
          REACT_APP_SHA: ${{ github.sha }}
          REACT_APP_REPOSITORY: ${{ github.repository }}
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
